// data.jsx — Speisekarte „Campedèl Hof"
// Trilingual (DE/IT/EN) menu. Diet tags + origin flag for filtering & badges.

const HOF_INTRO = {
  de: 'Ein Südtiroler Hofschank, in dem alles passt: saftige Wiesen, herrliche Aussicht, gutes Essen und ausgezeichneter Wein. Sie befinden sich im denkmalgeschützten Untergeschoss des Feuerhauses — dem Campedèl-Keller — umgeben von Mauern aus dem 13. Jahrhundert.',
  it: 'Un tipico Hofschank altoatesino dove tutto è in armonia: prati rigogliosi, una vista splendida, ottimo cibo e vino eccellente. Vi trovate nel piano interrato tutelato della casa del fuoco, la cosiddetta cantina Campedèl, circondati da mura del 13° secolo.',
  en: 'A South Tyrolean farm tavern where everything comes together: lush meadows, stunning views, excellent food, and outstanding wine. You are in the protected basement of the main house — the Campedèl cellar — surrounded by 13th-century walls.',
};

const UI_STRINGS = {
  open_menu:   { de: 'Speisekarte öffnen', it: 'Apri il menù', en: 'Open the menu' },
  todays:      { de: 'Tageskarte',          it: 'Piatti del giorno', en: "Today's specials" },
  menu:        { de: 'Speisekarte',         it: 'Menù',              en: 'Menu' },
  wines:       { de: 'Weinkarte',           it: 'Carta dei vini',    en: 'Wine list' },
  drinks:      { de: 'Getränke',            it: 'Bevande',           en: 'Drinks' },
  filters:     { de: 'Filter',              it: 'Filtri',            en: 'Filters' },
  veg:         { de: 'Vegetarisch',         it: 'Vegetariano',       en: 'Vegetarian' },
  vegan:       { de: 'Vegan',               it: 'Vegano',            en: 'Vegan' },
  gf:          { de: 'Glutenfrei',          it: 'Senza glutine',     en: 'Gluten-free' },
  lf:          { de: 'Laktosefrei',         it: 'Senza lattosio',    en: 'Lactose-free' },
  from_farm:   { de: 'Vom eigenen Hof',     it: 'Dal nostro maso',   en: 'From our farm' },
  house_made:  { de: 'Hausgemacht',         it: 'Fatto in casa',     en: 'House-made' },
  back:        { de: 'Zurück',              it: 'Indietro',          en: 'Back' },
  welcome:     { de: 'Willkommen im',       it: 'Benvenuti al',      en: 'Welcome to' },
  ingredients: { de: 'Zutaten',             it: 'Ingredienti',       en: 'Ingredients' },
  pairing:     { de: 'Empfehlung dazu',     it: 'In abbinamento',    en: 'Pairs well with' },
  today:       { de: 'Heute',               it: 'Oggi',              en: 'Today' },
  season:      { de: 'Frühling 2026',       it: 'Primavera 2026',    en: 'Spring 2026' },
  tagline:     { de: 'Südtiroler Hofschank · seit 2019',
                 it: 'Hofschank altoatesino · dal 2019',
                 en: 'South Tyrolean farm tavern · since 2019' },
  hours:       { de: 'Di–So · 11:30 – 22:00',
                 it: 'Mar–Dom · 11:30 – 22:00',
                 en: 'Tue–Sun · 11:30 – 22:00' },
  search:      { de: 'Suchen', it: 'Cerca', en: 'Search' },
  more:        { de: 'Mehr anzeigen', it: 'Mostra altro', en: 'Show more' },
};

// d = diet tags: 'veg' / 'vegan' / 'gf' / 'lf'
// h = vom eigenen Hof
// hm = hausgemacht
const CATEGORIES = [
  {
    id: 'cold',
    name: { de: 'Kalte Vorspeisen', it: 'Antipasti', en: 'Starters' },
    items: [
      { id: 'salad',     name: { de: 'Gemischter Salat', it: 'Insalata mista', en: 'Mixed salad' }, p: '6,00', d: ['veg','vegan','gf','lf'], photo: 'img/salad.jpg',
        desc: { de: 'Frische Saisonsalate aus dem eigenen Garten, mariniert mit hausgemachtem Kräuteressig und kaltgepresstem Öl.',
                it: 'Insalate di stagione del nostro orto, condite con aceto alle erbe fatto in casa e olio extravergine.',
                en: 'Seasonal salads from our kitchen garden, dressed with house herb vinegar and cold-pressed oil.' },
        ingredients: { de: ['Kopfsalat','Rucola','Cherrytomaten','Gurke','Karotten','Kräuteressig','Olivenöl','Kräuter'],
                       it: ['Lattuga','Rucola','Pomodorini','Cetriolo','Carote','Aceto alle erbe','Olio extravergine','Erbe'],
                       en: ['Lettuce','Rocket','Cherry tomatoes','Cucumber','Carrots','Herb vinegar','Olive oil','Fresh herbs'] } },
      { id: 'brett',     name: { de: 'Bretteljause mit Speck und Käse', it: 'Tagliere di speck con formaggi', en: 'Speck and cheese platter' }, p: '15,90', d: ['gf'], h: true, photo: 'img/brett.jpg',
        desc: { de: 'Hausgereifter Speck, Bergkäse, hausgemachtes Brot.',
                it: 'Speck stagionato in casa, formaggio di malga, pane fatto in casa.',
                en: 'House-aged speck, mountain cheese, homemade bread.' },
        ingredients: { de: ['Hausspeck','Bergkäse','Frischkäse','Hausgemachtes Brot','Senf','Essiggurken'],
                       it: ['Speck','Formaggio di malga','Formaggio fresco','Pane fatto in casa','Senape','Cetriolini'],
                       en: ['House speck','Mountain cheese','Cream cheese','Homemade bread','Mustard','Gherkins'] } },
      { id: 'tatar',     name: { de: 'Avokado-Tomatentatar mit Burrata und Wildkräutersalat',
                                  it: 'Tartare di avocado e pomodori con burrata e insalata di erbe selvatiche',
                                  en: 'Avocado & tomato tartare with burrata and wild herb salad' }, p: '16,90', d: ['veg'], photo: 'img/tatar.jpg',
        desc: { de: 'Cremig-frisches Tatar aus reifer Avokado und Tomaten, getoppt mit zartem Burrata und einem Nest aus wilden Wiesenkräutern.',
                it: 'Tartare fresca e cremosa di avocado maturo e pomodori, coronata da burrata morbida e un bouquet di erbe selvatiche.',
                en: 'A creamy fresh tartare of ripe avocado and tomatoes, crowned with soft burrata and a nest of wild herb salad.' },
        ingredients: { de: ['Avokado','Tomaten','Limette','Olivenöl','Basilikum','Burrata','Wildkräuter','Pinienkerne'],
                       it: ['Avocado','Pomodori','Lime','Olio extravergine','Basilico','Burrata','Erbe selvatiche','Pinoli'],
                       en: ['Avocado','Tomatoes','Lime','Olive oil','Basil','Burrata','Wild herbs','Pine nuts'] } },
    ],
  },
  {
    id: 'soup',
    name: { de: 'Suppen', it: 'Zuppe', en: 'Soups' },
    items: [
      { id: 'knoedel',   name: { de: 'Speckknödelsuppe', it: 'Canederli allo speck in brodo', en: 'Speck dumpling soup' }, p: '12,90', d: [], h: true, hm: true, photo: 'img/knoedel.jpg',
        desc: { de: 'Hausgemachte Knödel aus hausgereiftem Speck und altbackenem Brot, in einer klaren Rindsuppe vom eigenen Hofkalb.',
                it: 'Canederli fatti in casa con speck stagionato e pane raffermo, serviti in brodo di vitello chiaro del maso.',
                en: 'Homemade dumplings of house-aged speck and day-old bread, in a clear broth from our own farm veal.' },
        ingredients: { de: ['Hausspeck','Altbrot','Eier','Milch','Mehl','Rinderfond','Schnittlauch','Petersilie'],
                       it: ['Speck','Pane raffermo','Uova','Latte','Farina','Brodo di manzo','Erba cipollina','Prezzemolo'],
                       en: ['House speck','Day-old bread','Eggs','Milk','Flour','Beef broth','Chives','Parsley'] } },
      { id: 'spargel',   name: { de: 'Spargelcremesuppe mit Brotcroutons', it: 'Crema di asparagi con crostini', en: 'Cream of asparagus soup with croutons' }, p: '9,90', d: ['veg'], photo: 'img/spargel.jpg',
        desc: { de: 'Samtig-feine Crème aus frischen Eisacktaler Spargeln, abgerundet mit hausgemachten Buttercroutons.',
                it: 'Crema vellutata di asparagi freschi della Val d’Isarco, completata da crostini al burro fatti in casa.',
                en: 'A silky cream of fresh Eisack-valley asparagus, rounded off with house-made butter croutons.' },
        ingredients: { de: ['Weißspargel','Sahne','Butter','Schalotten','Gemüsefond','Croutons','Schnittlauch','Muskat'],
                       it: ['Asparagi bianchi','Panna','Burro','Scalogno','Brodo vegetale','Crostini','Erba cipollina','Noce moscata'],
                       en: ['White asparagus','Cream','Butter','Shallots','Vegetable broth','Croutons','Chives','Nutmeg'] } },
    ],
  },
  {
    id: 'primi',
    name: { de: 'Warme Vorspeisen', it: 'Primi piatti', en: 'First courses' },
    items: [
      { id: 'schlutz',   name: { de: 'Hausgemachte Schlutzkrapfen mit Butter und Reibkäse',
                                  it: 'Mezzelune con spinaci fatte in casa, burro fuso e parmigiano',
                                  en: 'Homemade Schlutzkrapfen with butter and grated cheese' },
        p: '15,50', d: ['veg'], hm: true, photo: 'img/schlutz.jpg',
        desc: { de: 'Halbmondförmige Teigtaschen mit Spinat- und Topfenfüllung — ein Südtiroler Klassiker, bei uns nach Großmutters Rezept gefaltet.',
                it: 'Mezzelune di pasta con ripieno di spinaci e ricotta — un classico altoatesino, piegate a mano secondo la ricetta della nonna.',
                en: 'Half-moon pasta pockets filled with spinach and quark — a South Tyrolean classic, folded by hand to grandmother\u2019s recipe.' },
        ingredients: { de: ['Hartweizen­teig','Spinat','Topfen','Bergbutter','Reibkäse','Schnittlauch'],
                       it: ['Pasta di grano','Spinaci','Ricotta','Burro di malga','Parmigiano','Erba cipollina'],
                       en: ['Durum pasta','Spinach','Quark','Mountain butter','Grated cheese','Chives'] },
        pairing: 'Sylvaner · Weingut Taschlerhof' },
      { id: 'knoedeltris', name: { de: 'Knödeltris mit Butter und Reibkäse',
                                    it: 'Tris di canederli con burro fuso e parmigiano',
                                    en: 'Trio of dumplings with butter and grated cheese' }, p: '16,50', d: ['veg'], hm: true, photo: 'img/knoedeltris.jpg',
        desc: { de: 'Drei Knödel — Speck, Käse und Spinat — an zerlassener Bergbutter und frisch geriebenem Parmesan.',
                it: 'Tris di canederli — speck, formaggio e spinaci — con burro di malga fuso e parmigiano grattugiato fresco.',
                en: 'A trio of dumplings — speck, cheese and spinach — with melted mountain butter and freshly grated Parmesan.' },
        ingredients: { de: ['Hausspeck','Bergkäse','Spinat','Altbrot','Eier','Milch','Bergbutter','Parmesan'],
                       it: ['Speck','Formaggio di malga','Spinaci','Pane raffermo','Uova','Latte','Burro di malga','Parmigiano'],
                       en: ['House speck','Mountain cheese','Spinach','Day-old bread','Eggs','Milk','Mountain butter','Parmesan'] } },
      { id: 'tortelloni',  name: { de: 'Hausgemachte Tortelloni mit Ricottafüllung, Bärlauch und Spargelragout',
                                    it: 'Tortelloni ripieni di ricotta con ragù di asparagi e aglio orsino',
                                    en: 'Homemade tortelloni with ricotta, wild garlic and asparagus ragout' }, p: '16,50', d: ['veg'], hm: true, photo: 'img/tortelloni.jpg',
        desc: { de: 'Saftiger Ricotta trifft auf frischen Bärlauch und ein duftendes Spargelragout — ganz hausgemacht, ganz frühlingshaft.',
                it: 'Ricotta succosa incontra aglio orsino fresco e un ragù profumato di asparagi — tutto fatto in casa, tutto primaverile.',
                en: 'Juicy ricotta meets fresh wild garlic and fragrant asparagus ragout — made entirely in house, entirely of spring.' },
        ingredients: { de: ['Hartweizenpasta','Ricotta','Bärlauch','Spargel','Butter','Parmesan','Olivenöl','Zitrone'],
                       it: ['Pasta di grano duro','Ricotta','Aglio orsino','Asparagi','Burro','Parmigiano','Olio extravergine','Limone'],
                       en: ['Durum pasta','Ricotta','Wild garlic','Asparagus','Butter','Parmesan','Olive oil','Lemon'] } },
      { id: 'risotto',     name: { de: 'Brennnessel-Risotto mit frischem Spargel',
                                    it: 'Risotto alle ortiche con asparagi freschi',
                                    en: 'Nettle risotto with fresh asparagus' }, p: '16,90', d: ['veg','gf'], photo: 'img/risotto.jpg',
        desc: { de: 'Cremiges Arborio-Risotto mit jungen Brennnesseln — intensiv und erdig, mit knackigem Spargel als Kontrast.',
                it: 'Risotto cremoso di riso Arborio con ortiche giovani — intenso e terroso, con asparagi croccanti a contrasto.',
                en: 'Creamy Arborio risotto with young nettles — intense and earthy, with crisp asparagus as a counterpoint.' },
        ingredients: { de: ['Arborio-Reis','Brennnesseln','Spargel','Weißwein','Parmesan','Bergbutter','Gemüsefond','Schalotten'],
                       it: ['Riso Arborio','Ortiche','Asparagi','Vino bianco','Parmigiano','Burro di malga','Brodo vegetale','Scalogno'],
                       en: ['Arborio rice','Nettles','Asparagus','White wine','Parmesan','Mountain butter','Vegetable broth','Shallots'] } },
    ],
  },
  {
    id: 'main',
    name: { de: 'Hauptspeisen', it: 'Piatti principali', en: 'Main courses' },
    items: [
      { id: 'entrecote',  name: { de: 'Entrecote vom Rind mit Kartoffelspalten, Salat und Kräuterbutter',
                                   it: 'Entrecote con spicchi di patate, insalata mista e burro alle erbe',
                                   en: 'Beef entrecote with potato wedges, mixed salad and herb butter' }, p: '28,50', d: ['gf'], h: true, photo: 'img/entrecote.jpg',
        desc: { de: 'Saftiges Ribeye vom eigenen Grauvieh, nach Wunsch gegrillt, mit Kräuterbutter, Salat und goldenen Kartoffelspalten.',
                it: 'Succoso entrecote dei nostri bovini grigi, grigliato a puntino, con burro alle erbe, insalata e spicchi di patate dorati.',
                en: 'Juicy ribeye from our own grey cattle, grilled to your liking, with herb butter, salad and golden potato wedges.' },
        ingredients: { de: ['Rinds-Entrecote','Kräuterbutter','Knoblauch','Rosmarin','Kartoffeln','Blattsalate','Meersalz','Pfeffer'],
                       it: ['Entrecote di manzo','Burro alle erbe','Aglio','Rosmarino','Patate','Insalata','Sale marino','Pepe'],
                       en: ['Beef entrecote','Herb butter','Garlic','Rosemary','Potatoes','Salad greens','Sea salt','Pepper'] } },
      { id: 'burger',     name: { de: '„Campedèl-Burger" vom eigenen Grauvieh',
                                   it: '«Campedèl Burger» con carne dei nostri bovini',
                                   en: '"Campedèl Burger" with our own grey-cattle beef' }, p: '18,90', d: [], h: true, hm: true, photo: 'img/burger.jpg',
        desc: { de: 'Mit hausgebackenem Brot, Speck, Bergkäse, Tomaten, roter Zwiebel, Salat und Kartoffelspalten.',
                it: 'Con pane fatto in casa, speck, formaggio, pomodori, cipolla rossa, insalata e spicchi di patate.',
                en: 'With homemade bread, bacon, mountain cheese, tomato, red onion, salad and potato wedges.' },
        ingredients: { de: ['Rindfleisch','Hausbackenes Brot','Hausspeck','Bergkäse','Tomaten','Rote Zwiebel','Salat','Kartoffelspalten'],
                       it: ['Manzo','Pane fatto in casa','Speck','Formaggio di malga','Pomodori','Cipolla rossa','Insalata','Spicchi di patate'],
                       en: ['Beef','Homemade bread','House speck','Mountain cheese','Tomatoes','Red onion','Lettuce','Potato wedges'] } },
      { id: 'pepper',     name: { de: 'Pfeffersteak „Campedèl", medium, mit Röstkartoffeln und Salat',
                                   it: 'Filetto al pepe verde «Campedèl», cottura media, con patate arrosto e insalata',
                                   en: '"Campedèl" pepper steak, medium, with roasted potatoes and salad' }, p: '34,00', d: ['gf'], h: true, photo: 'img/pepper.jpg',
        desc: { de: 'Zartes Rindsfilet vom Hofkalb, medium gebraten, in einem seidigen Grünpfeffer-Cognac-Jus — dazu Röstkartoffeln.',
                it: 'Filetto di manzo del maso, cottura media, in un sugo setoso di pepe verde e cognac — con patate arrosto.',
                en: 'Tender farm fillet cooked medium, in a silky green peppercorn and cognac jus — with roasted potatoes.' },
        ingredients: { de: ['Rindsfilet','Grüner Pfeffer','Cognac','Sahne','Butter','Röstkartoffeln','Blattsalate','Schalotten'],
                       it: ['Filetto di manzo','Pepe verde','Cognac','Panna','Burro','Patate arrosto','Insalata','Scalogno'],
                       en: ['Beef fillet','Green pepper','Cognac','Cream','Butter','Roasted potatoes','Salad greens','Shallots'] } },
      { id: 'gulasch',    name: { de: 'Hofeigenes Rindsgulasch mit zwei Speckknödeln',
                                   it: 'Gulasch di manzo della casa con due canederli allo speck',
                                   en: 'Homemade beef goulash with two speck dumplings' }, p: '19,50', d: [], h: true, hm: true, photo: 'img/gulasch.jpg',
        desc: { de: 'Lang geschmortes Rindfleisch aus eigenem Bestand in einer tiefroten Paprikasauce — nach altem Hofrezept.',
                it: 'Manzo del maso brasato a lungo in una salsa rossa di peperoni — secondo l’antica ricetta del maso.',
                en: 'Slow-braised beef from our own herd in a deep red paprika sauce — our time-honoured farm recipe.' },
        ingredients: { de: ['Rindfleisch','Paprika','Zwiebeln','Knoblauch','Tomaten','Rotwein','Lorbeer','Kümmel'],
                       it: ['Manzo','Peperoni','Cipolle','Aglio','Pomodori','Vino rosso','Alloro','Cumino'],
                       en: ['Beef','Peppers','Onions','Garlic','Tomatoes','Red wine','Bay leaf','Caraway'] } },
      { id: 'wiener',     name: { de: 'Wienerschnitzel vom Hofkalb mit Pommes und Preiselbeermarmelade',
                                   it: 'Cotoletta di vitello del maso con patatine e mirtilli rossi',
                                   en: 'Viennese schnitzel of farm veal with fries and cranberry jam' }, p: '22,90', d: [], h: true, photo: 'img/wiener.jpg',
        desc: { de: 'Goldbraun paniertes Kalbsschnitzel vom eigenen Hofkalb, knusprig und butterzart — mit Pommes und Preiselbeer-Marmelade.',
                it: 'Cotoletta di vitello del maso impanata e dorata, croccante e delicatissima — con patatine e mirtilli rossi.',
                en: 'Golden-breaded veal schnitzel from our own farm calf, crisp outside, butter-tender within — with fries and cranberries.' },
        ingredients: { de: ['Kalbfleisch','Semmelbrösel','Eier','Butterschmalz','Zitrone','Pommes','Preiselbeeren','Petersilie'],
                       it: ['Vitello','Pangrattato','Uova','Burro chiarificato','Limone','Patatine','Mirtilli rossi','Prezzemolo'],
                       en: ['Veal','Breadcrumbs','Eggs','Clarified butter','Lemon','Fries','Cranberries','Parsley'] } },
      { id: 'spargel-main', name: { de: 'Frische Stangenspargel mit Hausschinken, Naturkartoffeln und Bozner Sauce',
                                     it: 'Asparagi bianchi freschi con prosciutto della casa, patate lesse e salsa bolzanina',
                                     en: 'Fresh white asparagus with homemade ham, boiled potatoes and Bozner sauce' }, p: '23,90', d: ['gf'], h: true, photo: 'img/spargel-main.jpg',
        desc: { de: 'Weißer Stangenspargel aus dem Eisacktal, mit zarter Bozner Sauce, gewürztem Hausschinken und Naturkartoffeln.',
                it: 'Asparagi bianchi della Val d’Isarco, con delicata salsa bolzanina, prosciutto della casa e patate lesse.',
                en: 'White asparagus from the Eisack valley with delicate Bozner sauce, seasoned house ham and boiled potatoes.' },
        ingredients: { de: ['Weißspargel','Hausschinken','Naturkartoffeln','Eier','Butter','Senf','Schnittlauch','Zitrone'],
                       it: ['Asparagi bianchi','Prosciutto della casa','Patate lesse','Uova','Burro','Senape','Erba cipollina','Limone'],
                       en: ['White asparagus','House ham','Boiled potatoes','Eggs','Butter','Mustard','Chives','Lemon'] } },
    ],
  },
  {
    id: 'kids',
    name: { de: 'Für unsere kleinen Gäste', it: 'Per i bambini', en: 'For kids' },
    items: [
      { id: 'k-wiener', name: { de: 'Wienerschnitzel vom Hofkalb mit Pommes', it: 'Cotoletta di vitello del maso con patatine', en: 'Veal schnitzel with fries' }, p: '15,00', d: [], h: true, photo: 'img/k-wiener.jpg',
        desc: { de: 'Zartes Kalbsschnitzel aus unserem Hof, paniert und goldbraun gebraten, dazu knusprige Pommes frites.',
                it: 'Tenera cotoletta di vitello del maso, impanata e dorata, con patatine fritte croccanti.',
                en: 'Tender veal schnitzel from our farm, breaded and golden-fried, with crispy french fries.' },
        ingredients: { de: ['Kalbfleisch','Semmelbrösel','Eier','Butterschmalz','Pommes','Zitrone'],
                       it: ['Vitello','Pangrattato','Uova','Burro chiarificato','Patatine','Limone'],
                       en: ['Veal','Breadcrumbs','Eggs','Clarified butter','Fries','Lemon'] } },
      { id: 'k-spag',   name: { de: 'Spaghetti mit Tomatensauce oder Ragu', it: 'Spaghetti al pomodoro o ragù', en: 'Spaghetti with tomato or ragù' }, p: '9,50', d: ['veg'], photo: 'img/k-spag.jpg',
        desc: { de: 'Lange Spaghetti mit hausgemachter Tomatensauce aus Hofgarten-Tomaten oder herzem Fleischragù.',
                it: 'Spaghetti lunghi con salsa di pomodoro del nostro orto oppure con ricco ragù di carne.',
                en: 'Long spaghetti with homemade tomato sauce from our garden tomatoes or a hearty meat ragù.' },
        ingredients: { de: ['Spaghetti','Tomaten','Knoblauch','Basilikum','Olivenöl','Parmesan'],
                       it: ['Spaghetti','Pomodori','Aglio','Basilico','Olio extravergine','Parmigiano'],
                       en: ['Spaghetti','Tomatoes','Garlic','Basil','Olive oil','Parmesan'] } },
      { id: 'k-wurst',  name: { de: 'Grillwurst mit Pommes', it: 'Würstel alla griglia con patatine', en: 'Grilled sausage with fries' }, p: '9,50', d: [], photo: 'img/k-wurst.jpg',
        desc: { de: 'Saftige Grillwurst vom Holzkohlegrill, knusprig und aromatisch, mit goldenen Pommes frites.',
                it: 'Würstel succosi alla griglia a carbone, croccanti e saporiti, con patatine fritte dorate.',
                en: 'Juicy sausages from the charcoal grill, crispy and aromatic, served with golden french fries.' },
        ingredients: { de: ['Schweinswurst','Pommes','Senf','Ketchup'],
                       it: ['Würstel di maiale','Patatine','Senape','Ketchup'],
                       en: ['Pork sausage','Fries','Mustard','Ketchup'] } },
      { id: 'k-fries',  name: { de: 'Pommes frites', it: 'Patatine fritte', en: 'French fries' }, p: '6,00', d: ['veg','vegan'], photo: 'img/k-fries.jpg',
        desc: { de: 'Goldbraune, knusprige Pommes frites aus Hofkartoffeln — der Liebling unserer kleinen Gäste.',
                it: 'Patatine fritte dorate e croccanti da patate del maso — il preferito dei piccoli ospiti.',
                en: 'Golden crispy french fries from farm potatoes — a firm favourite with our little guests.' },
        ingredients: { de: ['Kartoffeln','Sonnenblumenöl','Meersalz'],
                       it: ['Patate','Olio di girasole','Sale marino'],
                       en: ['Potatoes','Sunflower oil','Sea salt'] } },
    ],
  },
  {
    id: 'dessert',
    name: { de: 'Dessert', it: 'Dolci', en: 'Desserts' },
    items: [
      { id: 'buchteln', name: { de: 'Buchteln mit Vanillesauce', it: 'Buchteln con crema alla vaniglia', en: 'Buchteln with vanilla sauce' }, p: '9,50', d: ['veg'], hm: true, photo: 'img/buchteln.jpg',
        desc: { de: 'Fluffige Germknödel aus dem Backrohr, zart und süß, mit einer samtigen Vanillesauce übergossen.',
                it: 'Soffici buchteln al forno, delicati e dolcemente lievitati, nappati con una vellutata crema alla vaniglia.',
                en: 'Fluffy oven-baked yeast buns, tender and sweetly aromatic, bathed in a velvety vanilla sauce.' },
        ingredients: { de: ['Germteig','Butter','Vanillezucker','Milch','Eier','Weizenmehl','Vanillesauce','Puderzucker'],
                       it: ['Pasta lievitata','Burro','Zucchero vanigliato','Latte','Uova','Farina','Crema vaniglia','Zucchero a velo'],
                       en: ['Yeast dough','Butter','Vanilla sugar','Milk','Eggs','Flour','Vanilla sauce','Icing sugar'] } },
      { id: 'icehimb',  name: { de: 'Vanilleeis mit heißen Himbeeren', it: 'Gelato alla vaniglia con lamponi caldi', en: 'Vanilla ice cream with warm raspberries' }, p: '8,50', d: ['veg','gf'], photo: 'img/icehimb.jpg',
        desc: { de: 'Cremiges Vanilleeis mit frisch aufgekochten, süß-säuerlichen Himbeeren — ein Hauch Sommer auf dem Teller.',
                it: 'Cremoso gelato alla vaniglia con lamponi cotti al momento, dolci e aciduli — un assaggio d’estate nel piatto.',
                en: 'Creamy vanilla ice cream with freshly simmered sweet-tart raspberries — a taste of summer on the plate.' },
        ingredients: { de: ['Vanilleeis','Himbeeren','Zucker','Butter','Vanille','Zitronensaft'],
                       it: ['Gelato alla vaniglia','Lamponi','Zucchero','Burro','Vaniglia','Succo di limone'],
                       en: ['Vanilla ice cream','Raspberries','Sugar','Butter','Vanilla','Lemon juice'] } },
      { id: 'sorbet',   name: { de: 'Zitronensorbet mit Limoncello', it: 'Sorbetto al limone con Limoncello', en: 'Lemon sorbet with Limoncello' }, p: '7,90', d: ['veg','vegan','gf','lf'], photo: 'img/sorbet.jpg',
        desc: { de: 'Eisig-frisches Zitronensorbet mit einem Schuss Limoncello — leicht, erfrischend, ein perfekter Abschluss.',
                it: 'Sorbetto al limone ghiacciato e fresco con un tocco di Limoncello — leggero, rinfrescante, il finale perfetto.',
                en: 'Ice-cold lemon sorbet with a splash of Limoncello — light, refreshing, the perfect ending.' },
        ingredients: { de: ['Zitronensorbet','Limoncello','Zitronenschale','Zucker','Minze'],
                       it: ['Sorbetto al limone','Limoncello','Scorza di limone','Zucchero','Menta'],
                       en: ['Lemon sorbet','Limoncello','Lemon zest','Sugar','Mint'] } },
      { id: 'strudel',  name: { de: 'Apfelstrudel mit Vanillesauce', it: 'Strudel di mele con crema alla vaniglia', en: 'Apple strudel with vanilla sauce' }, p: '5,90', d: ['veg'], hm: true, photo: 'img/strudel.jpg',
        desc: { de: 'Knuspriger Blätterteig mit Zimtäpfeln und Rosinen, hausgemacht nach altem Campedèl-Rezept — mit Vanillesauce.',
                it: 'Pasta sfoglia croccante con mele e cannella e uvetta, fatto in casa secondo l’antica ricetta Campedèl — con crema vaniglia.',
                en: 'Crispy pastry with cinnamon apples and raisins, house-made to the old Campedèl recipe — with vanilla sauce.' },
        ingredients: { de: ['Strudelteig','Äpfel','Zimt','Zucker','Rosinen','Semmelbrösel','Butter','Vanillesauce'],
                       it: ['Pasta strudel','Mele','Cannella','Zucchero','Uvetta','Pangrattato','Burro','Crema vaniglia'],
                       en: ['Strudel pastry','Apples','Cinnamon','Sugar','Raisins','Breadcrumbs','Butter','Vanilla sauce'] } },
      { id: 'creme',    name: { de: 'Crème brûlée mit frischen Erdbeeren', it: 'Crème brûlée con fragole fresche', en: 'Crème brûlée with fresh strawberries' }, p: '7,90', d: ['veg','gf'], photo: 'img/creme.jpg',
        desc: { de: 'Klassische Crème brûlée mit karamellisierter Zuckerkruste — serviert mit frischen Erdbeeren aus dem Hofgarten.',
                it: 'Classica crème brûlée con crosta di caramello croccante — servita con fragole fresche del nostro orto.',
                en: 'Classic crème brûlée with a caramelised sugar crust — served with fresh strawberries from our kitchen garden.' },
        ingredients: { de: ['Sahne','Eidotter','Zucker','Vanille','Karamell','Erdbeeren'],
                       it: ['Panna','Tuorli','Zucchero','Vaniglia','Caramello','Fragole'],
                       en: ['Cream','Egg yolks','Sugar','Vanilla','Caramel','Strawberries'] } },
    ],
  },
];

const DRINKS = {
  hot: [
    { id:'espresso',   n: { de:'Espresso',          it:'Espresso',           en:'Espresso' },          p:'1,80', photo:'img/drink-espresso.jpg' },
    { id:'macchiato',  n: { de:'Macchiato',         it:'Macchiato',          en:'Macchiato' },         p:'1,80', photo:'img/drink-macchiato.jpg' },
    { id:'doppio',     n: { de:'Doppelter Espresso',it:'Espresso doppio',    en:'Double espresso' },   p:'3,60', photo:'img/drink-doppio.jpg' },
    { id:'cappuccino', n: { de:'Cappuccino',        it:'Cappuccino',         en:'Cappuccino' },        p:'3,00', photo:'img/drink-cappuccino.jpg' },
    { id:'latte',      n: { de:'Latte Macchiato',   it:'Latte macchiato',    en:'Latte macchiato' },   p:'3,00', photo:'img/drink-latte.jpg' },
    { id:'schokolade', n: { de:'Heiße Schokolade',  it:'Cioccolata calda',   en:'Hot chocolate' },     p:'4,00', photo:'img/drink-schokolade.jpg' },
    { id:'tee',        n: { de:'Tee (Früchte · Kräuter · Schwarz)', it:'Tè (frutta · erbe · nero)', en:'Tea (fruit · herbal · black)' }, p:'3,00', photo:'img/drink-tee.jpg' },
  ],
  // multi-size sets: each entry has `sizes` array
  water: {
    sizes: ['0,3 l', '0,5 l', '1,0 l'],
    items: [
      { id:'mineralwasser', n: { de:'Mineralwasser', it:'Acqua minerale', en:'Mineral water' }, p:['2,00','2,50','5,00'], photo:'img/drink-mineralwasser.jpg' },
      { id:'wasser-natur',  n: { de:'Wasser Natur',  it:'Acqua naturale', en:'Still water'    }, p:['2,00','2,50','5,00'], photo:'img/drink-wasser-natur.jpg' },
      { id:'apfelsaft',     n: { de:'Apfelsaft',     it:'Succo di mela',  en:'Apple juice'    }, p:['3,00','5,00','9,00'], photo:'img/drink-apfelsaft.jpg' },
      { id:'skiwasser',     n: { de:'Skiwasser',     it:'Skiwasser',      en:'Skiwasser'      }, p:['3,50','6,00','12,00'], photo:'img/drink-skiwasser.jpg' },
    ],
  },
  juices: {
    sizes: ['0,3 l', '0,5 l'],
    items: [
      { id:'himbeersaft',  n: { de:'Himbeersaft',   it:'Succo di lampone',  en:'Raspberry juice'    }, p:['3,00','5,00'], photo:'img/drink-himbeersaft.jpg' },
      { id:'holundersaft', n: { de:'Holundersaft',  it:'Succo di sambuco',  en:'Elderflower juice'  }, p:['3,00','5,00'], photo:'img/drink-holundersaft.jpg' },
      { id:'melissensaft', n: { de:'Melissensaft',  it:'Succo di melissa',  en:'Lemon-balm juice'   }, p:['3,00','5,00'], photo:'img/drink-melissensaft.jpg' },
      { id:'colasaft',     n: { de:'Colasaft',      it:'Succo di mela e cola', en:'Cola juice'      }, p:['3,00','5,00'], photo:'img/drink-colasaft.jpg' },
    ],
  },
  beer: {
    sizes: ['0,3 l', '0,5 l'],
    items: [
      { id:'forst-kronen', n: { de:'Kronen Forst Bier', it:'Birra Forst Kronen', en:'Forst Kronen beer' }, p:['3,80','6,00'], photo:'img/drink-bier-forst.jpg' },
      { id:'radler',       n: { de:'Radler',            it:'Radler',             en:'Shandy (Radler)'   }, p:['3,80','6,00'], photo:'img/drink-bier-radler.jpg' },
      { id:'hefeweizen',   n: { de:'Hefeweizen',        it:'Hefeweizen',         en:'Wheat beer'        }, p:['3,80','6,00'], photo:'img/drink-bier-hefeweizen.jpg' },
      { id:'bier-alkfrei', n: { de:'Alkoholfreies Bier',it:'Birra analcolica',   en:'Alcohol-free beer' }, p:['3,50','6,00'], photo:'img/drink-bier-alkfrei.jpg' },
    ],
  },
  aperitif: [
    { id:'campedeller',     n: { de:'Aperitif Campedeller',     it:'Aperitivo Campedeller',     en:'Campedeller aperitif' },          p:'5,00', sig:true, photo:'img/drink-campedeller.jpg' },
    { id:'hugo',            n: { de:'Hugo (Holunderspritz)',     it:'Hugo',                      en:'Hugo (elderflower spritz)' },     p:'5,00',           photo:'img/drink-hugo.jpg' },
    { id:'veneziano',       n: { de:'Veneziano (Aperolspritz)', it:'Veneziano',                 en:'Aperol spritz' },                 p:'5,00',           photo:'img/drink-veneziano.jpg' },
    { id:'prosecco',        n: { de:'Prosecco',                 it:'Prosecco',                  en:'Prosecco' },                      p:'4,00',           photo:'img/drink-prosecco.jpg' },
    { id:'sanbitter',       n: { de:'Sanbitter Weiß',           it:'Sanbittèr bianco',          en:'Sanbittèr white' },               p:'4,00',           photo:'img/drink-sanbitter.jpg' },
    { id:'gin-hendricks',   n: { de:'Gin Tonic · Hendrick’s', it:'Gin Tonic · Hendrick’s', en:'Gin & Tonic · Hendrick’s' }, p:'10,00',   photo:'img/drink-gin.jpg' },
    { id:'gin-illusionist', n: { de:'Gin Tonic · Illusionist',  it:'Gin Tonic · Illusionist',   en:'Gin & Tonic · Illusionist' },     p:'14,00',          photo:'img/drink-gin.jpg' },
  ],
  digestif: [
    { id:'hausschnaps',  n: { de:'Hausschnaps',  it:'Grappa della casa',   en:'House schnapps' },       p:'3,50', sig:true, photo:'img/drink-schnaps-a.jpg' },
    { id:'latschen',     n: { de:'Latschen',     it:'Latschen (mugo)',     en:'Mountain pine' },          p:'3,50',           photo:'img/drink-latschen.jpg' },
    { id:'nusseler',     n: { de:'Nusseler',     it:'Liquore alle noci',   en:'Walnut liqueur' },         p:'3,50',           photo:'img/drink-schnaps-c.jpg' },
    { id:'zirmschnaps',  n: { de:'Zirmschnaps',  it:'Cembro',              en:'Swiss pine schnapps' },    p:'3,50',           photo:'img/drink-zirmschnaps.jpg' },
    { id:'limoncello',   n: { de:'Limoncello',   it:'Limoncello',          en:'Limoncello' },             p:'3,50',           photo:'img/drink-limoncello.jpg' },
    { id:'williams',     n: { de:'Williams',     it:'Williams',            en:'Williams' },               p:'3,50',           photo:'img/drink-williams.jpg' },
    { id:'enzian',       n: { de:'Enzian',       it:'Genziana',            en:'Gentian' },                p:'3,50',           photo:'img/drink-enzian.jpg' },
    { id:'treber',       n: { de:'Treber',       it:'Grappa di vinacce',   en:'Grappa di vinaccia' },     p:'3,50',           photo:'img/drink-treber.jpg' },
    { id:'heuschnaps',   n: { de:'Heuschnaps',   it:'Distillato di fieno', en:'Hay schnapps' },           p:'3,50',           photo:'img/drink-heuschnaps.jpg' },
    { id:'branca-menta', n: { de:'Branca Menta', it:'Branca Menta',        en:'Branca Menta' },           p:'4,00',           photo:'img/drink-branca-menta.jpg' },
    { id:'fernet',       n: { de:'Fernet Branca',it:'Fernet Branca',       en:'Fernet Branca' },          p:'4,00',           photo:'img/drink-fernet.jpg' },
    { id:'cynar',        n: { de:'Cynar',        it:'Cynar',               en:'Cynar' },                  p:'4,00',           photo:'img/drink-cynar.jpg' },
    { id:'montenegro',   n: { de:'Montenegro',   it:'Montenegro',          en:'Montenegro' },             p:'4,00',           photo:'img/drink-montenegro.jpg' },
  ],
};

const WINES = {
  bubbles: [
    { id:'arunda',           name:'Arunda Brut',               maker:'Sektkellerei Arunda',             region:'Südtirol DOC · brut',                       grapes:'CH · PB · PN', sizes:[{s:'0,75 l', p:'39,00'}],                                                             photo:'img/wein-arunda.jpg' },
    { id:'zemmer',           name:'Zemmer Millesimato',        maker:'Weingut Peter Zemmer',            region:'Vino Spumante di Qualità · brut',            grapes:'CH · RI',      sizes:[{s:'0,75 l', p:'29,00'},{s:'Glas', p:'5,00'}],                                       photo:'img/wein-zemmer.jpg' },
  ],
  white: [
    { id:'michelstrunk-weiss', name:'Michelstrunk Weiss',      maker:'Kellerei St. Michael-Eppan',      region:'Vino Bianco d’Italia · trocken',        house:true,            sizes:[{s:'1,0 l', p:'18,00'},{s:'1/2 l', p:'10,00'},{s:'1/4 l', p:'5,50'},{s:'Glas', p:'2,70'}], photo:'img/wein-michelstrunk-weiss.jpg' },
    { id:'t-cuvee',          name:'T Cuvée Weiss',             maker:'Kellerei Tramin',                 region:'Weinberge Dolomiten IGT · trocken',           grapes:'CH · SB · PB', sizes:[{s:'0,75 l', p:'26,00'},{s:'Glas', p:'5,00'}],                                       photo:'img/wein-t-cuvee.jpg' },
    { id:'gewuerztraminer',  name:'Gewürztraminer',            maker:'Kellerei St. Michael-Eppan',      region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'29,00'}],                                                             photo:'img/wein-gewuerztraminer.jpg' },
    { id:'schulthaus',       name:'Schulthaus Weissburgunder', maker:'Kellerei St. Michael-Eppan',      region:'Südtirol DOC · trocken',                     grapes:'Pinot Bianco', sizes:[{s:'0,75 l', p:'30,00'},{s:'Glas', p:'5,00'}],                                        photo:'img/wein-schulthaus.jpg' },
    { id:'sylvaner',         name:'Sylvaner',                  maker:'Weingut Taschlerhof',             region:'Südtirol Eisacktaler DOC · trocken',                                  sizes:[{s:'0,75 l', p:'32,00'}],                                                             photo:'img/wein-sylvaner.jpg' },
    { id:'kerner',           name:'Kerner',                    maker:'Zu Tschötsch',                    region:'Weinberge Dolomiten IGT · halbtrocken',                               sizes:[{s:'0,75 l', p:'34,00'},{s:'Glas', p:'5,50'}],                                        photo:'img/wein-kerner.jpg' },
    { id:'sauvignon',        name:'Sauvignon',                 maker:'Weingut Putzenhof',               region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'30,00'},{s:'Glas', p:'5,00'}],                                        photo:'img/wein-sauvignon.jpg' },
    { id:'sanctvalentin',    name:'Sanct Valentin Sauvignon',  maker:'Kellerei St. Michael-Eppan',      region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'41,00'}],                           note:'Falstaff 92 · Parker 93 · Suckling 93', photo:'img/wein-sanctvalentin.jpg' },
    { id:'riesling',         name:'Riesling',                  maker:'Weingut Strasserhof',             region:'Südtirol Eisacktaler DOC · trocken',                                  sizes:[{s:'0,75 l', p:'33,00'}],                           note:'Falstaff 92',              photo:'img/wein-riesling.jpg' },
    { id:'fellis',           name:'Fellis Chardonnay Riserva', maker:'Weingut Bessererhof',             region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'33,00'}],                                                             photo:'img/wein-fellis.jpg' },
  ],
  red: [
    { id:'michelstrunk-rot', name:'Michelstrunk Rot',          maker:'Kellerei St. Michael-Eppan',      region:'Vino Rosso d’Italia · trocken',         house:true,            sizes:[{s:'1,0 l', p:'18,00'},{s:'1/2 l', p:'10,00'},{s:'1/4 l', p:'5,50'},{s:'Glas', p:'2,70'}], photo:'img/wein-michelstrunk-rot.jpg' },
    { id:'zeder',            name:'Zeder',                     maker:'Weingut Kornell',                 region:'Südtirol DOC · trocken',                     grapes:'ME · CS · LA', sizes:[{s:'0,75 l', p:'30,00'},{s:'Glas', p:'5,00'}],                                        photo:'img/wein-zeder.jpg' },
    { id:'soma',             name:'Soma',                      maker:'Kellerei Kurtatsch',              region:'Südtirol DOC · trocken',                     grapes:'ME · CF · CS', sizes:[{s:'0,75 l', p:'40,00'}],                                                             photo:'img/wein-soma.jpg' },
    { id:'cabernet-riserva', name:'Cabernet Riserva',          maker:'Weingut Wassererhof',             region:'Südtirol DOC · trocken',                     grapes:'CS · CF',      sizes:[{s:'0,75 l', p:'44,00'}],                           note:'Falstaff 93',              photo:'img/wein-cabernet-riserva.jpg' },
    { id:'magdalener',       name:'St. Magdalener',            maker:'Kellerei St. Michael-Eppan',      region:'Südtirol DOC · trocken',                     grapes:'VT · LA',      sizes:[{s:'0,75 l', p:'27,00'},{s:'Glas', p:'5,00'}],                                        photo:'img/wein-magdalener.jpg' },
    { id:'roan',             name:'Roan Zweigelt',             maker:'Weingut Bessererhof',             region:'Weinberge Dolomiten IGT · trocken',                                   sizes:[{s:'0,75 l', p:'33,00'}],                                                             photo:'img/wein-roan.jpg' },
    { id:'pinot-noir',       name:'Pinot Noir',                maker:'Kellerei St. Michael-Eppan',      region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'30,00'},{s:'Glas', p:'5,00'}],                                        photo:'img/wein-pinot-noir.jpg' },
    { id:'marith',           name:'Marith Blauburgunder',      maker:'Weingut Kornell',                 region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'34,00'}],                                                             photo:'img/wein-marith.jpg' },
    { id:'glen',             name:'Glen Blauburgunder Riserva',maker:'Kellerei Kurtatsch',              region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'39,00'}],                                                             photo:'img/wein-glen.jpg' },
    { id:'lagrein',          name:'Lagrein',                   maker:'Kellerei St. Michael-Eppan',      region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'29,00'},{s:'Glas', p:'5,00'}],                                        photo:'img/wein-lagrein.jpg' },
    { id:'karl-lagrein',     name:'Karl Lagrein Riserva',      maker:'Weingut Bergmannhof',             region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'42,00'}],                                                             photo:'img/wein-karl-lagrein.jpg' },
    { id:'huberfeld',        name:'Huberfeld Merlot',          maker:'Kellerei St. Pauls',              region:'Südtirol DOC · trocken',                                              sizes:[{s:'0,75 l', p:'31,00'}],                                                             photo:'img/wein-huberfeld.jpg' },
    { id:'san-leonardo',     name:'Terre di San Leonardo',     maker:'Tenuta San Leonardo, Trient',     region:'Weinberge Dolomiten IGT · trocken',          grapes:'CS · ME · CRE',sizes:[{s:'0,75 l', p:'31,00'}],                                                             photo:'img/wein-san-leonardo.jpg' },
    { id:'amarone',          name:'Amarone',                   maker:'Casa Vinicola Bennati, Venetien', region:'Amarone d. Valpolicella DOCG · trocken',     grapes:'CV · RON · MOL',sizes:[{s:'0,75 l', p:'40,00'}],                                                            photo:'img/wein-amarone.jpg' },
  ],
};

// Grape-abbreviation legend (footer of wine list)
const WINE_LEGEND = [
  ['CF','Cabernet Franc'], ['CH','Chardonnay'], ['CRE','Carménère'],
  ['CS','Cabernet Sauvignon'], ['CV','Corvina'], ['LA','Lagrein'],
  ['ME','Merlot'], ['MOL','Molinara'], ['PB','Weissburgunder · Pinot Bianco'],
  ['PN','Pinot Noir · Pinot Nero'], ['RI','Riesling'], ['RON','Rondinella'],
  ['SB','Sauvignon Blanc'], ['VT','Vernatsch · Schiava'],
];

// Tageskarte / Specials — frühlingshaft 2026
const SPECIALS = {
  date: { de: 'Freitag, 8. Mai 2026', it: 'Venerdì 8 maggio 2026', en: 'Friday, 8 May 2026' },
  intro: { de: 'Heute aus der Hofküche — vorwiegend mit Zutaten aus dem eigenen Garten und dem Eisacktal.',
           it: 'Oggi dalla cucina del maso — con ingredienti del nostro orto e della Val d\u2019Isarco.',
           en: 'From the farm kitchen today — using produce from our garden and the Eisack valley.' },
  items: [
    { kind:'soup', refId:'spargel' },
    { kind:'primi', refId:'risotto' },
    { kind:'main', refId:'spargel-main' },
    { kind:'dessert', refId:'sorbet' },
  ],
};

Object.assign(window, { MENU: CATEGORIES, CATEGORIES, DRINKS, WINES, WINE_LEGEND, SPECIALS, UI_STRINGS, HOF_INTRO });
